# Generated by Django 5.0.6 on 2024-05-21 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_note_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_mood",
                    models.CharField(
                        choices=[
                            ("Задоволення", "Задоволення"),
                            ("Сум", "Сум"),
                            ("Злість", "Злість"),
                            ("Страх", "Страх"),
                            ("Відраза", "Відраза"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
