import { Inter } from 'next/font/google';
import './globals.css';
import LoginRegister from './(public)/LoginRegister/page';
import Image from 'next/image';
import profilePic from '@/src/assets/other/profilePic.png';
import Link from 'next/link';
import { Provider } from 'react-redux';
import { makeStore } from '@/service/store';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
