import { Inter } from 'next/font/google';
import Image from 'next/image';
import profilePic from '@/src/assets/other/profilePic.png';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PrivateLayout({ children }) {
  return (
    <div className={inter.className}>
      <div className="flex justify-center">
        <div className=" flex flex-row w-[80%]   items-center justify-between my-2">
          <Link href={'/Home'}>
            <h1 className="text-3xl font-semibold ">
              Daily<span className="text-[#0094FF]">Mindfullness</span>
            </h1>
          </Link>

          <div className="flex flex-row items-center gap-2">
            <Link href={'/signOut'}>sign out</Link>
          </div>
        </div>
      </div>

      {children}
    </div>
  );
}
